#!/bin/bash
#this programme is free  and can be modified
#please send me mail for bug repprt to perform
#for any question you can contact the author


t1="|                                                                                   |"
t2="|                                                                                   |"
t3=" ->Xvpn developped by jean koffi mail: <hill.flame1er@gmail.com>: Guela ni man tobpo<-"

#this section print xvpn on middle of sceen 
#->get scren with
COL1=$(tput cols)
printf "\e[34m%*s\n" $((($COL1+${#t1})/2)) "$t1"
printf "%*s\n" $((($COL1+${#t2})/2)) "$t2"
printf "%*s\e[0m\n" $((($COL1+${#t3})/2)) "$t3"

#->define print variable
echo1=" X     P      X           X       XVPNXVPN      X     X"        
echo2="  V   V        V         V        V       X     VV    V"   
echo3="   P P          P       P         PVPNXVPN      P P   P"   
echo4="    N            N     N          N             N  N  N"     
echo5="   X X            X   X           X             X   X X"   
echo6="  V   V            V V            V             V    VV"        
echo7=" P     P            P             P             P     P"              											
      												
COL=$(tput cols)
printf "\e[33m%*s\n" $((($COL+${#echo1})/2)) "$echo1"												
printf "\e[33m%*s\n" $((($COL+${#echo2})/2)) "$echo2"												
printf "\e[97m%*s\n" $((($COL+${#echo3})/2)) "$echo3"												
printf "\e[97m%*s\n" $((($COL+${#echo4})/2)) "$echo4"												
printf "\e[97m%*s\n" $((($COL+${#echo5})/2)) "$echo5"												
printf "\e[92m%*s\n" $((($COL+${#echo6})/2)) "$echo6"												
printf "\e[92m%*s\e[0m\n" $((($COL+${#echo7})/2)) "$echo7"												
#this section set umask of run file umask
umask 077
#this section difine config file path
source conf_dir/Xvpn.conf
#this section increment index var
i=0
vpnlist_index=0

#this section create tmp file
#pref=`shuf -i298674-97655677988765554 -n1`
tmp_file=`mktemp -t`

#this section list vpn files and put output in tmp file
ls -1 $XVPN_DIR > $tmp_file
#read file content to get vpn list
while read LINE1 
do 
vpnlist_index=$(($vpnlist_index+1))
vpnlist[$vpnlist_index]=$LINE1
choice_tab[$vpnlist_index]=$vpnlist_index
done < $tmp_file
#format output to remove .ovpn
sed -i 's/\.ovpn/\ /' $tmp_file
#read file contents to print vpn list

echo ""
choose="Your VPN list are:"
COL3=$(tput cols)
printf "\e[31m%*s\e[0m\n" $((($COL3+${#choose})/2)) "$choose"
 
while read LINE2 
do 
i=$(($i+1))
if [ $(($i%2)) -eq 0 ] 
then
col="\e[97m"
else
col="\e[95m"
fi
echo -e " $col$i-$LINE2\e[0m"

done < $tmp_file

#supression du fichier temporaire à la sortie
trap 'rm -rf "$tmp_file"' EXIT
echo "enter your choose now"
read vpn_number
while [[ ${choice_tab[$vpn_number]} != $vpn_number ]]; do
echo "wrong choice!!!!!!!!!!!!!!!"
echo "retype your choice"
read vpn_number
done

#échapper tous les espaces des fichiers
#vpn_file=`ls "$XVPN_DIR/${vpnlist[$vpn_number]}"|sed -e "s/\ /\\ /"`
conf_file=`ls "$XVPN_DIR/${vpnlist[$vpn_number]}"|sed -e 's/\ /\\ /'`
echo " Your conf file $conf_file"
if [ -f "$conf_file" ]; then
openvpn --config "$conf_file"
else
echo "Configuration file not found"
fi
